/*
 * This source file was generated by the Gradle 'init' task
 */
package catan.main;

import java.util.concurrent.TimeUnit;

import catan.board.CatanBoard;
import catan.player.CatanPlayer;
import catan.player.SmartRandomPlayer;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        CatanBoard board = new CatanBoard();
        board.populateBoard();
        //board.printBoard();
        //board.displayBoard();
        //board.printAdjacentTilesAndEdges();
        CatanPlayer randomPlayer = new SmartRandomPlayer();
        board.placeStartingPositions(new CatanPlayer[]{randomPlayer,randomPlayer,randomPlayer,randomPlayer});
        int currentPlayer = 0;
        for(int i = 0; i < 1000; i++) {
            try {
                TimeUnit.MILLISECONDS.sleep(200);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("Turn " + i);
            currentPlayer = board.takeTurn(currentPlayer, randomPlayer);
            board.displayBoard();
        }
        
        board.printAvailableVerticesAndEdges();
    }
}
